version: 2.1

commands:
  install_asdf:
    steps:
      - run:
          name: install asdf
          command: |
            ASDF_ROOT="$(mktemp -d)/asdf"
            # `mktemp` on codecov doesn't support long options, use short
            # options instead.

            PLATFORM="$(uname | tr '[:upper:]' '[:lower:]')"
            ARCH="$(uname -m)"
            case "$ARCH" in
            x86_64) ARCH="amd64" ;;
            esac

            ASDF_PKG="${ASDF_ROOT}/pkg/asdf.tar.gz"
            curl --output "${ASDF_PKG}" --create-dirs --location --silent --show-error "https://github.com/asdf-vm/asdf/releases/download/v0.17.0/asdf-v0.17.0-${PLATFORM}-${ARCH}.tar.gz"

            ASDF_BIN="${ASDF_ROOT}/bin"
            mkdir -p "${ASDF_BIN}"
            tar x -f "${ASDF_PKG}" -C "${ASDF_BIN}"
            chmod +x "${ASDF_BIN}/asdf"

            echo 'export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"' >> "$BASH_ENV"
            echo "export PATH=\"${ASDF_BIN}:\$PATH\"" >> "$BASH_ENV"

  asdf_plugin_test:
    steps:
      - run:
          name: test
          command: |
            eval "PLUGIN_DIR=${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"
            # Have to expand `~` manually.  CircleCI does not use the
            # canonical path.
            #
            # https://discuss.circleci.com/t/circle-working-directory-doesnt-expand/17007/5
            asdf plugin test zls "$PLUGIN_DIR" --asdf-plugin-gitref "$CIRCLE_SHA1" "zls --version" # DevSkim: ignore DS126858
            #
            # Fix false positive from DevSkim.
            #
            # `CIRCLE_SHA1` is just a variable, not an algorithm.
            #
            # https://github.com/microsoft/DevSkim/wiki/Suppressions
            # https://github.com/Microsoft/DevSkim/blob/main/guidance/DS126858.md
            # https://circleci.com/docs/variables/#built-in-environment-variables

jobs:
  MegaLinter:
    docker:
      - image: oxsecurity/megalinter:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo "export CI_JOB_URL=$CIRCLE_BUILD_URL" >> "$BASH_ENV"
            # Export `CI_JOB_URL` for MegaLinter API Reporter
            echo "export DEFAULT_WORKSPACE=$CIRCLE_WORKING_DIRECTORY" >> "$BASH_ENV"
            . "$BASH_ENV"
      - run:
          name: Run MegaLinter
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports

  commitlint:
    docker:
      - image: commitizen/commitizen:latest
        # checkov:skip=CKV_CIRCLECIPIPELINES_1:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          command: |
            cz check --rev-range 401cb2d..HEAD

  plugin_test:
    docker:
      - image: cimg/base:current
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - install_asdf
      - asdf_plugin_test

  plugin_test_macos:
    macos:
      xcode: 15.0.0
    steps:
      - checkout
      - run:
          name: install GNU tar
          command: |
            brew update
            brew install gnu-tar
            echo "export PATH=\"$(brew --prefix)/opt/gnu-tar/libexec/gnubin\":\"\$PATH\"" >> "$BASH_ENV"
            # https://circleci.com/docs/env-vars/#parameters-and-bash-environment
      - install_asdf
      - asdf_plugin_test

  lint:
    docker:
      - image: cimg/base:current
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - install_asdf
      - run:
          name: install asdf plugins
          command: |
            asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
            asdf plugin add shfmt https://github.com/luizm/asdf-shfmt.git
            asdf install
      - run:
          command: |
            scripts/lint.bash

workflows:
  MegaLinter:
    jobs:
      - MegaLinter:
          context: megalinter

  Lint:
    jobs:
      - lint
      - commitlint

  Build:
    jobs:
      - plugin_test
      - plugin_test_macos
