name: Build

on:
  - push
  - pull_request

permissions: read-all

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: install GNU tar
        # GitHub added [1] GNU tar into macos runner but name it "gtar" which
        # is incompatible with the plugin scripts.
        #
        # [1]: https://github.com/actions/runner-images/issues/1534
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install gnu-tar
          echo "$(brew --prefix)/opt/gnu-tar/libexec/gnubin" >> "$GITHUB_PATH"
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
          # https://formulae.brew.sh/formula/gnu-tar
          # https://docs.brew.sh/Manpage#--prefix---unbrewed---installed-formula-
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: zls --version
